[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements/prod.txt"

[deploy]
startCommand = "uvicorn src.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
restartPolicyType = "always"

[environments.production]
variables = { PYTHONPATH = "/app/src" }